name: deploy

on:
  # Trigger the workflow on push to main branch and tutorial path
  push:
    branches:
      - main
    paths:
      - notebooks/**

# This job installs dependencies, build the jupyter notebook, and pushes it to `render`, a new `branch`
jobs:
  build:
    name: Setup
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Set up conda and dependencies
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ./environment.yml
          environment-name: jupytergis-examples
          condarc: |
            channels:
              - conda-forge
      # Build the book
      - name: Build the jupyter book
        run: |
          wget https://raw.githubusercontent.com/qgis/QGIS-Training-Data/master/exercise_data/raster/SRTM/srtm_41_19.tif -O notebooks/srtm_41_19.tif
          jupyter-book build notebooks
      # Deploy the book's HTML to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: notebooks/_build/html
          force_orphan: true
